Add Hide Tab Index and Hide Tab Close Button
Eugeny/terminus pull request #3142
Opened 2020-11-16 20:20 UTC by pinpins

This adds functionality to Hide Tab Index and to hide Tab Close(x) Button regardless of template used.

2020-11-16 20:56 UTC, Eugeny requested changes
Thank you for your contribution! Take a look at the linter output and I've also added a few comments here and there

2020-11-16 20:56 UTC, Eugeny commented on terminus-terminal/src/components/appearanceSettingsTab.component.pug
> +        (ngModelChange)='config.save(); config.requestRestart()',
Restart shouldn't be required if you bind directly to the settings in `TabHeaderComponent`

2020-11-16 20:56 UTC, Eugeny commented on terminus-core/src/components/tabHeader.component.pug
> +button(*ngIf='tab.showCloseButton==true',(click)='app.closeTab(tab, true)') &times;
You can make `config` `public` and use `!config.store.terminal.disableCloseButton` here directly

2020-11-16 20:56 UTC, Eugeny commented on terminus-terminal/src/components/appearanceSettingsTab.component.pug
> +        .title Disable Tab Index
Please use `Sentence case`

2020-11-17 07:17 UTC, pinpins commented
Thanks for review and comments, still learning your implementation for the first time. If all ok with latest commit, please cut a release, would love to use those new features.

2020-12-06 16:25 UTC, merged

2020-12-06 16:28 UTC, Eugeny commented
@allcontributors please add @pinpins for code